services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    command: >
      bash -c "python manage.py migrate &&
               python manage.py load_weather_data &&
               python manage.py runserver 0.0.0.0:8000"
