# Generated by Django 4.2.7 on 2025-08-02 14:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeatherParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('unit', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(blank=True, null=True)),
                ('value', models.FloatField()),
                ('source_url', models.URLField()),
                ('data_file', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='weather_api.weatherparameter')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='weather_api.region')),
            ],
            options={
                'ordering': ['-year', '-month', 'region__name', 'parameter__name'],
                'indexes': [models.Index(fields=['region', 'parameter'], name='weather_api_region__a18e2d_idx'), models.Index(fields=['year', 'month'], name='weather_api_year_63b027_idx'), models.Index(fields=['created_at'], name='weather_api_created_ac1c3b_idx')],
                'unique_together': {('region', 'parameter', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField()),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('last_data_year', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_api.weatherparameter')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_api.region')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('region', 'parameter')},
            },
        ),
    ]
