# Generated by Django 5.0.4 on 2025-08-04 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0002_alter_datasource_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
        migrations.AlterModelOptions(
            name='weatherparameter',
            options={},
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_api.weatherparameter'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_api.region'),
        ),
        migrations.AlterField(
            model_name='weatherparameter',
            name='unit',
            field=models.CharField(default='°C', max_length=20),
        ),
    ]
